// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXsEdF0Gh5Jb7nH3fZ_xbBdPZpL73ywwE',
    appId: '1:822201491207:web:0bf403b9277ba144252fa2',
    messagingSenderId: '822201491207',
    projectId: 'practicamov1',
    authDomain: 'practicamov1.firebaseapp.com',
    storageBucket: 'practicamov1.firebasestorage.app',
    measurementId: 'G-BC7C3CT7K8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV6a41SA2WFmKhzNDUgQkUwcH_wnpnog8',
    appId: '1:822201491207:android:9c51de86e5df7765252fa2',
    messagingSenderId: '822201491207',
    projectId: 'practicamov1',
    storageBucket: 'practicamov1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvb6rOTr-_kt2tHZpIb4hIyEJD4Dw_VoQ',
    appId: '1:822201491207:ios:54eda53bbf09a302252fa2',
    messagingSenderId: '822201491207',
    projectId: 'practicamov1',
    storageBucket: 'practicamov1.firebasestorage.app',
    iosBundleId: 'com.example.alarma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvb6rOTr-_kt2tHZpIb4hIyEJD4Dw_VoQ',
    appId: '1:822201491207:ios:54eda53bbf09a302252fa2',
    messagingSenderId: '822201491207',
    projectId: 'practicamov1',
    storageBucket: 'practicamov1.firebasestorage.app',
    iosBundleId: 'com.example.alarma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXsEdF0Gh5Jb7nH3fZ_xbBdPZpL73ywwE',
    appId: '1:822201491207:web:36861831ee22157c252fa2',
    messagingSenderId: '822201491207',
    projectId: 'practicamov1',
    authDomain: 'practicamov1.firebaseapp.com',
    storageBucket: 'practicamov1.firebasestorage.app',
    measurementId: 'G-0PKV19PMHT',
  );

}